[project]
name = "analise-deadfish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dateparser>=1.2.2",
    "httpx>=0.28.1",
    "parsel>=1.10.0",
    "polars>=1.32.3",
]
